### ISSUE TITLE
Some convenient buttons

### ISSUE THREAD

**Issue by Ivoz** [asdfjkl/jerry#11]
Hi there, I have a suggestion to add to the GUI.

I know you have an idea to keep it as simple and elegant as possible, however, hear me out.

I'm thinking from the point of view where I mostly want to do everything with my mouse. All basic functionality should be easy with that. Frees up my other hand for other things, or maybe sometimes I'm lazy and don't want to do to use the keyboard for the keyboard shortcuts either. Maybe, say with other hand I am holding open a page of a chess book, eating a cracker or writing things down.

What is hard at the moment is going advancing to the next move in the game with just the mouse - you have to find, and click on just the right move notation in the move list.

It would be nice therefore to have some advance / rewind move buttons, as well as go-to start and go-to end. Just like a media player. Then I can just click-click-click in one spot to advance or backup moves very quickly.

The other critical functions, I think, are switching between the primary modes. Whether I want to play (honestly I don't think I'd be using the program for that hardly ever.. playing against computer is almost never fun), or just enter moves, or turn analysis on.

Unless I'm missing things, "Analysis Mode" and "Enter Moves" are really just other names for "Turn Engine On / Off" It could be one toggle button, or two (...or four for the four modes) buttons for both of those. But being able to turn engine on / off without having to go to a menu would be nice.

If you really wanted enough buttons to say, fill up a tool bar, you could also have ones for Save PGN, Open PGN, New Game.

Otherwise, if you really don't want a lot of buttons, even adding forward / back move, start of game / end of game, and Engine on / off buttons would really improve usability for when you just want to operate the program with a mouse.

Position of buttons there are a few options, I would suggest under the board or in a toolbar over the board. If you wanted to be super flexible, you could have a toolbar, and an option to enable / disable it.

Cheers.

**Comment by partik1** [comment]
I think this project is dead. Last time he made any changes was 4 months ago and he's not answering to github's issues. Hopefully someone can pick it up where he left.

**Comment by Ivoz** [comment]
He answered my comment in #9 quite recently. Not everyone gets the time, or the motivation, to always be working on their personal projects.

**Comment by asdfjkl** [comment]
@partik1: I have a life. This is free software. I'm doing my best, but this isn't a commercial next day business support. Check my blog on https://buildingjerry.wordpress.com/ to see what's going on.
@Ivoz  This addresses some of the issues you mentioned: https://buildingjerry.wordpress.com/2016/01/09/current-status/
Nevertheless I am always looking into ways to make the gui more accessible. Mouse-whell back/forward is planned, and I'll take your suggestions into consideration for sure.

In general: I am focusing all my efforts into the rewrite in C++, because that's absolutely crucial to have a stable basis for the future. Hence the current stall for this repo.

**Comment by asdfjkl** [comment]
closed, as there are plenty of buttons in the v3 beta.
