### ISSUE TITLE
100 percent cpu usage on Linux

### ISSUE THREAD

**Issue by ExtremeCoolDude** [asdfjkl/jerry#112]
Stockfish is off but the jar uses 100% cpu anyway, pc gets very hot upto 72C in my case. Using OpenJDk 11. The only warning is `(java:12299): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`
 but its related to gtk theme. Not sure what's causing the issue.

**Comment by ExtremeCoolDude** [comment]
Ran the exe in windows 7 vm, CPU usage immediately starting the program jumps to 57% to 100%, (engine is off).

**Comment by asdfjkl** [comment]
This is currently expected behaviour, since the engine is off, but the thread that takes care of starting/stopping/interfacing with the engine is not.

Therefore on an N-core system, expect 1/N CPU usage. Are you using a single-core system?

In future I will look in putting the thread to sleep if no engine is running...

**Comment by ExtremeCoolDude** [comment]
Thank you! That makes sense, in the 2 core vm it was 57%, I'm using 4 core 8 thread and the laptop  gets uncomfortably hot with top command showing 100%.  I guess I'll just use cpulimit tool while stockfish is not running.

**Comment by asdfjkl** [comment]
(reminder to myself:
todo: 
- kill engine thread if engine is not currently running. 
- check for startup/stop delays due to thread-starting/stopping when starting/stopping engine

**Comment by asdfjkl** [comment]
(probably fixed in 2083610e81058610a7656e16a6e1a9eb9246a0cf but needs more testing! )

**Comment by ExtremeCoolDude** [comment]
Perfect so far! Thanks a lot!
