### ISSUE TITLE
Engine parameters not applied in Analysis Mode

### ISSUE THREAD

**Issue by KirkF** [asdfjkl/jerry#118]
Running master branch on Windows 10. 

I have external Stockfish 13 configured with engine parameters of 8 threads and 2 gigs of ram. This works properly when manually turning on the engine on a position (as I can see CPU and Memory usage in Task Manager) but when using Analysis Mode the external engine is being used but it's only using one core and very little memory, running significantly fewer kn/s

**Comment by asdfjkl** [comment]
I understand there is a different behavior when you click on the on/off button for the engine in the lower left vs when you click "anlysis" in the "Mode"-Menu?

Or is this w.r.t. to "Game Analysis". For automatic "Game Analysis" this is currently (still) expected behavior, will change in the next release...

**Comment by KirkF** [comment]
@asdfjkl yes, for the latter. Did not realize that was on the roadmap. Thanks

**Comment by asdfjkl** [comment]
(cf. 025acd734101691e778c9394304b94fec8a7f92f )
