### ISSUE TITLE
Compiling ecocode.cpp with latest clang in Xcode8 incredibly slow

### ISSUE THREAD

**Issue by cuddlestmonkey** [asdfjkl/jerry#28]
I realise this is not a bug with Jerry itself but thought it worth recording in case anyone else hits the issue.

Compiling current release 3.0.6 with latest Qt 5.7 and Xcode 8 on OSX, all is well (barring the odd compiler warning) except when it comes to ecocode.cpp. This sends clang into a long think. 

If I chop the static QMap definition down to 100 lines or so it compiles ok, but the compilation time seems to be geometric as the line count grows.

**Comment by asdfjkl** [comment]
interesting and thanks for reporting. Unfortunately I cannot look into that - my build chain uses the (ancient) Xcode 4.6.3, where this bug does not occur. Unfortunately my machine is too old to run a more recent version of macOS (and in any event, I prefer to build on older systems to ensure maximum compatibility)

**Comment by jerry-chess** [comment]
I've filed a bug report here https://bugreports.qt.io/browse/QTBUG-57672

(not sure where the appropriate place is, Apple, since they apparently use a custom version of clang, Qt, since it happens with QMap, or clang).

If you happen to have the time - does the the behavior happen in general with initializer lists (e.g. with std::map), or just with QMap?

**Comment by asdfjkl** [comment]
Due to a lack Apple hardware, I will no longer create builds for macOS or support macOS in any way. Previous builds were done on a hacked virtual machine running Mountain Lion, but dev tools are now so old that I cannot use current builds of Qt anymore. Hence this longstanding bug is closed.
