### ISSUE TITLE
pixmap based boards have wrong resource path on OSX

### ISSUE THREAD

**Issue by cuddlestmonkey** [asdfjkl/jerry#29]
Hi,

Building latest sources (3.0.6) on OSX I noticed that the pixmap based board styles like wood and marble didn't work.

I fixed it by replacing calls like `QPixmap(DARK_SQUARE_WOOD)` with `QPixmap(ResourceFinder::getPath() + DARK_SQUARE_WOOD)` everywhere. But perhaps there is a more elegant solution.

**Comment by asdfjkl** [comment]
I've implemented that quick fix and added a new macOS build. Note to myself: Implement proper solution in future, e.g. using .qrc files.

One more thing: On my (ancient) Mountain Lion, "Old"-Style piece images are not rendered correctly. However I am not sure what the issue is, as the underlying .svg files are not rendered properly in Finder, too. This only affects the old-style images, not Merida or USCF.

Can you confirm that? Are you running sierra?

**Comment by cuddlestmonkey** [comment]
I'm running El Capitan. The old style pieces (Leipzig) render fine there. They also render ok in Finder. 

However, the SVG depends on having the font "DiagramTTOldstyle" installed on your system - so probably this is the actual problem.

Merida and USCF are self-sufficient SVGs - they don't need any font installed.

I note that the "old" pieces were created using a different version of inkscape from that used for the other two. So possibly this is an issue of export settings.

**Comment by asdfjkl** [comment]
thx, that's probably the issue. Will prob. remove Leipzig style pieces, since the availability and license of DiagramTTOldstyle is unclear...

**Comment by cuddlestmonkey** [comment]
Should be possible to load into inkscape and re-export... might give it a go. Nothing to lose.

**Comment by asdfjkl** [comment]
Due to a lack Apple hardware, I will no longer create builds for macOS or support macOS in any way. Previous builds were done on a hacked virtual machine running Mountain Lion, but dev tools are now so old that I cannot use current builds of Qt anymore. Hence this longstanding bug is closed.
