### ISSUE TITLE
Issues with packaging for AUR

### ISSUE THREAD

**Issue by Atrament666** [asdfjkl/jerry#48]
I am trying to create a PKGBUILD file for [AUR](https://aur.archlinux.org/) (Archlinux User Repository), to clone and build Jerry directly from Github, but I am having couple issues with it:

1. The version number - It's quite common in PKGBUILD to obtain the version number from a tag with `git describe --tags` command, but this command in Jerry repository currently returns Unsorted_Alphas-18-g77fb91c which is not very useful. Would it be possible to create a more usable tag, something like "v3.2.0" or "3.2.0"?

2. The internal engine - where does it come from? I was through the repository there and back couple of times and I just can't find it. I can see in model/internalengine.cpp that it is expected on Linux in /usr/games/stockfish, but how is it supposed to get there? Btw this hardcoded path for the internal engine isn't very good, it would be nice to make the internal engine part of the application resources with the Qt resources system, or make it configurable. 

Thanks

**Comment by asdfjkl** [comment]
1.) The version number - I will tag the next version accordingly. Note that the last stable version is 3.1.0. I am currently preparing for 3.2.0, but as always, I am behind schedule
2.) The internal engine is stockfish-chess. Since Stockfish is readily available on Linux and debian is my main focus, I simply set a dependency on the Stockfish package when building the .deb. I don't think it makes much sense to make Stockfish part of the application ressources (as opposed to Windows and macOS). Concerning the path: I cannot forsee all locations on all distributions on Linux where Stockfish might be installed. Also querying the system is somewhat awkward (i.e. which/ or whereis), since each and every Linux distro is different. My suggestion would be that you manually patch the path according to the stockfish Arch package.

**Comment by Atrament666** [comment]
Thanks for the reply,
I didn't realise that 'Internal' for Linux means that it comes from the package system, that makes much more sense then having it as a resource! AUR provides a [stockfish](https://aur.archlinux.org/packages/stockfish/) package, currently in version 10, I will make it a dependency for Jerry and patch the path in model/internalengine.cpp as you suggested.

**Comment by asdfjkl** [comment]
Thanks for the effort. Looking forward to see arch packages. Let me know if you encounter any difficulties.
