### ISSUE TITLE
Support for Retina Display

### ISSUE THREAD

**Issue by mikhorvath** [asdfjkl/jerry#7]
Please make it support Retina on Mac.

Great app!!

**Comment by asdfjkl** [comment]
I'll look into it. I doubt that I can support this however: To implement and test, I need a Retina-Mac, and at the moment there is no way I can afford one...

**Comment by sshivaji** [comment]
I can possible help with this too, any idea of exactly what u need for retina support (I have a retina mac)? You want the board or notation to be in retina?

**Comment by mikhorvath** [comment]
I would prefer if the whole app would support retina, so everything looks nice on a retina display. But the pieces are the most visible, which are not optimized for retina.

Thanks!!

**Comment by asdfjkl** [comment]
I am currently rewriting the whole application in C++/Qt5, whereas the current (2.0) version is in python/Qt4. Qt5 has support for retina displays ( http://doc.qt.io/qt-5/highdpi.html ), so please have some patience :-)

**Comment by mikhorvath** [comment]
Of course and thanks!! :)

**Comment by asdfjkl** [comment]
cf. https://buildingjerry.wordpress.com/2016/08/16/towards-high-resolution-displays/ for the current state.

**Comment by asdfjkl** [comment]
Version 3.0.5 @ https://github.com/asdfjkl/jerry/releases/tag/v.305 has rudimentary (beta) support for High-Resolution Displays (i.e. Retina on OS X, High-Dpi on Windows). Feedback is welcome.

**Comment by asdfjkl** [comment]
Jerry 3.1.0 has support for HighDPI display on both Linux, Windows, and macOS due to the underlying features of recent versions of Qt. Due to a lack Apple hardware however, I will no longer create builds for macOS or support macOS in any way. Previous builds were done on a hacked virtual machine running Mountain Lion, but dev tools are now so old that I cannot use current builds of Qt anymore. Hence this longstanding bug is closed.
