### ISSUE TITLE
Jerry 4.0.0  for 32 bit

### ISSUE THREAD

**Issue by esocrates** [asdfjkl/jerry#86]
Could you please compile Jerry 4..0.0 for 32 bit if possible? 
Thanks in advance

Regards

**Comment by asdfjkl** [comment]
That's a won't fix, sorry. I highly recommend to upgrade to a 64 bit OS.

The reason is that there are no 32 bit builds of JavaFX on Maven Central (see e.g. here https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/15.0.1/ )

This means, it's impossible to use Maven as a build-system in an automatic way. 

There are indeed 32 bit builds of JavaFX https://gluonhq.com/products/javafx/ and AdoptOpenJDK https://adoptopenjdk.net/releases.html, but this means creating manual builds and manual packaging. If someone wants to do this, I'll appreciate that - but as for myself, as long as the situation on maven central doesn't change, I will not provide 32 bit builds.
