### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by inorick** [asdfjkl/jerry#92]
I noticed that Jerry is available as a Snap package 👍
Having it also on ([Flathub](https://flathub.org/home)) would immediately make it available to almost all Linux users.

**Comment by asdfjkl** [comment]
Won't fix. Currently Flatpak's infrastructure is insufficient. Since JavaFX is out of the JDK, it requires platform dependent binaries.

Thus in order for jerry to be packaged as a flatpak I need either a) flatpaks sdk to include maven, so JavaFX can be included via maven during build time or b) (much better) JavaFX included in the flatpak sdk (cf https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/issues/1 )

I'll monitor this, but for now it's Snap only. Moreover snap support is actually quite good among Linux distributions nowadays . https://snapcraft.io/docs/installing-snapd

**Comment by PlatonB** [comment]
@asdfjkl Gnome Chess, KNights, CoreChess, and ChessMD are already available on Flathub, which indicates that chess GUIs can be successfully packaged in flatpak.
